//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        public int id_Libro { get; set; }
        public Nullable<int> id_autor { get; set; }
        public Nullable<int> id_editorial { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> año { get; set; }
        public string genero { get; set; }
        public Nullable<int> numero_paginas { get; set; }

        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
    }

}
